ip-whitelist:
  - "192.168.1.88"

ooc-webhook: "https://discordapp.com/api/webhooks/704786445721665587/UkuJkt3dLPM8ZwwKPZ6oO5O8G1Gs3ddHz-JwWk66__keHSmSgbAuBmPvk5CQ7aa894pr"
ahelp-webhook: "https://discordapp.com/api/webhooks/704786123150327890/jGMqave54wid8bLZSKfyo5AC7CaJvfIoIQFkFnWv3H42zX-TQ2m2YWU9V0yoZzGvuvKu"
